<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>turing.tu4</string>

        <key>fileTypes</key>
        <array>
            <string>tu4</string>
        </array>

        <key>name</key>
        <string>Turing file</string>

        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>\b[0-9]{2}\b</string>
                <key>name</key>

                <string>info-token</string>
            </dict>                
            <dict>
                <key>match</key>
                <string>\b//.*\b</string>
                <key>name</key>
                <string>comment</string>
            </dict>                          
        </array>
        <key>uuid</key>
        <string>FF0550E0-3A29-11E3-AA6E-0800200C9A77</string>
    </dict>
</plist>